#!/bin/bash
echo """
 _                     _
(_)                   | |
 _ _ __  ___  ___  ___| |
| | '_ \/ __|/ _ \/ __| __|
| | | | \__ \  __/ (__| |
|_|_| |_|___/\___|\___|\__|v1.0

Bug Bounty Scanner - Jdksec 2019
"""
echo "---------------------------------------------------------------"
echo "[+] Enter Targets name: "
echo "---------------------------------------------------------------"
read -p "" file
mkdir /root/BugBounty/Scans/$file
cd /root/BugBounty/Scans/$file
read -p "[+] Press enter to add your targets:" null
nano ./Targets.txt
cat Targets.txt > Whois.txt
echo "[+] Ensure you are in a tmux session and have configured your scans!"
sleep 10
echo "[+] VPN Connection status:"  | tee -a Scanner.log
expressvpn status
echo "[+] Your current IP address is: "  | tee -a Scanner.log
curl ifconfig.co  | tee -a Scanner.log
echo "[+] Performing speedtest: "  | tee -a Scanner.log
curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -  | tee -a Scanner.log
echo "[+] Continuing with current connection in 10 seconds: " 
sleep 10
echo "[+] Subdomain Bruteforce started $(date)" | tee -a Scanner.log
for Target in $(cat Targets.txt)
do
#Uncomment the scan you want
gobuster -m dns -w /root/BugBounty/Tools/Payloads/Subdomains-Small.lst -u $Target -i | tee -a Scanner.log | tee -a Subdomains.lst
#gobuster -m dns -w /root/BugBounty/Tools/Payloads/Subdomains-Medium.lst -u $Target -i | tee -a Scanner.log | tee -a Subdomains.lst
#gobuster -m dns -w /root/BugBounty/Tools/Payloads/Subdomains-Large.lst -u $Target -i | tee -a Scanner.log | tee -a Subdomains.lst
done
cat Targets.txt >> Targets.tmp
cat Subdomains.lst | grep Found | cut -d " " -f 2 >> Targets.tmp
cat Targets.tmp | sort -u > Targets.txt
rm Targets.tmp
echo "[+] The following Targets will be scanned:" | tee -a Scanner.log
cat Targets.txt | tee -a Scanner.log
echo "[+] Checking ownership: " | tee -a Scanner.log
sleep 10
for Target in $(cat Whois.txt)
do 
echo $Target | tee -a Ownership.txt  | tee -a Scanner.log
whois $Target | grep -E "Registrant Organization:|Admin Organization:|Registrant Email:|Admin Email:" | tee -a Ownership  | tee -a Scanner.log
sleep 1
done
echo "[+] Resolving IP addresses for Masscan"  | tee -a Scanner.log
for i in $(cat Targets.txt)
do host $i| awk '/has address/ {print $4}' | tee -a IPs.tmp
done 
cat IPs.tmp | sort -u > IPs.txt
rm IPs.tmp
echo "[+] Scanning with Masscan:"  | tee -a Scanner.log
masscan -iL IPs.txt -p10000,10243,1025,1026,1029,1030,1033,1034,1036,1038,110,1100,111,1111,113,119,123,135,137,139,143,1433,1434,1521,15567,161,1748,1754,1808,1809,199,20048,2030,2049,21,2100,22,22000,2222,23,25,25565,27900,2869,3128,3268,3269,32768,32843,32844,32846,3306,3339,3366,3372,3389,3573,35826,3632,36581,389,4190,43862,43871,44048,443,4443,4445,445,45295,4555,4559,464,47001,49152,49153,49154,49155,49156,49157,49158,49159,49160,49165,49171,49182,49327,49664,49665,49666,49667,49668,49669,49670,5000,5038,53,5353,5357,54987,55030,55035,55066,55067,55097,55104,55114,55116,55121,55138,55146,55167,55184,5722,5800,58633,587,5900,59010,59195,593,5985,6001,6002,6003,6004,6005,6006,6007,6008,6010,6011,6019,6144,631,636,64327,64337,6532,7411,745,7778,80,82,83,84,85,86,87,8000,8014,808,8080,81,8192,8228,88,8443,8008,8888,9389,9505,993,995 | tee -a MasscanList.txt
#masscan -iL IPs.txt -p0-1024 | tee -a MasscanList.txt
#masscan -iL IPs.txt -p0-10000 | tee -a MasscanList.txt 
#masscan -iL IPs.txt -p0-65535 | tee -a MasscanList.txt 
echo "[+] Services found:" | tee -a Scanner.log
cat MasscanList.txt | grep Discovered | awk '{print $6":"$4}' | cut -d "/" -f 1 | tee -a Scanner.log
echo "[+] Starting scans"  | tee -a Scanner.log
for Target in $(cat Targets.txt)
do
echo "---------------------------------------------------------------" | tee -a Scanner.log
echo "[+] $Target - Scanned: $(date)" | tee -a Scanner.log
echo "---------------------------------------------------------------"  | tee -a Scanner.log
echo ""  | tee -a Scanner.log
echo "---------------------------------------------------------------" | tee -a Scanner.log
echo "[+] TCP Scan Started: $(date)"  | tee -a Scanner.log
echo "---------------------------------------------------------------"  | tee -a Scanner.log
#Uncomment the scan you want
#Super fast scan
nmap -Pn -sSVC -p 10000,10243,1025,1026,1029,1030,1033,1034,1036,1038,110,1100,111,1111,113,119,123,135,137,139,143,1433,1434,1521,15567,161,1748,1754,1808,1809,199,20048,2030,2049,21,2100,22,22000,2222,23,25,25565,27900,2869,3128,3268,3269,32768,32843,32844,32846,3306,3339,3366,3372,3389,3573,35826,3632,36581,389,4190,43862,43871,44048,443,4443,4445,445,45295,4555,4559,464,47001,49152,49153,49154,49155,49156,49157,49158,49159,49160,49165,49171,49182,49327,49664,49665,49666,49667,49668,49669,49670,5000,5038,53,5353,5357,54987,55030,55035,55066,55067,55097,55104,55114,55116,55121,55138,55146,55167,55184,5722,5800,58633,587,5900,59010,59195,593,5985,6001,6002,6003,6004,6005,6006,6007,6008,6010,6011,6019,6144,631,636,64327,64337,6532,7411,745,7778,80,82,83,84,85,86,87,8000,8014,808,8080,81,8192,8228,88,8443,8008,8888,9389,9505,993,995 -oN $Target-01-NmapTCP.txt $Target  | tee -a Scanner.log
#Fast scan
#nmap -Pn -sSVC --top-ports 1000 -oN $Target-01-NmapTCP.txt $Target  | tee -a Scanner.log
#Full scan
#nmap -Pn -sSVC -p- -oN $Target-01-NmapTCP.txt $Target  | tee -a Scanner.log
echo "---------------------------------------------------------------"  | tee -a Scanner.log
echo "[+] UDP Scan Started: $(date)"  | tee -a Scanner.log
echo "---------------------------------------------------------------"  | tee -a Scanner.log
#Uncomment the scan you want
#Fast scan
nmap -sUV -sC --top-ports 10 -oN $Target-02-NmapUDP.txt $Target  | tee -a Scanner.log
#Deep scan
#nmap -sUV -sC --top-ports 200 -oN $Target-02-NmapUDP.txt $Target  | tee -a Scanner.log
echo "---------------------------------------------------------------"  | tee -a Scanner.log
echo "[+] Nikto Scan Started: $(date)"  | tee -a Scanner.log
echo "---------------------------------------------------------------"  | tee -a Scanner.log
nikto -maxtime 10m -ask no -p 80,443 -h $Target | tee $Target-03-Nikto.txt  | tee -a Scanner.log
echo "---------------------------------------------------------------"  | tee -a Scanner.log
echo "[+] SSL Scan Started: $(date)"  | tee -a Scanner.log
echo "---------------------------------------------------------------"  | tee -a Scanner.log
sslscan --no-colour --show-certificate $Target | grep -E "Signature Algorithm:|Altnames: |Heartbleed" | grep -v "    " | tee $Target-04-SSLScan.txt  | tee -a Scanner.log
echo "---------------------------------------------------------------"  | tee -a Scanner.log
echo "[+] Directory Scan Started: $(date)"  | tee -a Scanner.log
echo "---------------------------------------------------------------"  | tee -a Scanner.log
#Uncomment the size of the dictionary you want
#Small wordlist
gobuster -u http://$Target/ -w /root/BugBounty/Tools/Payloads/DirectoryList-Small.lst -q -e -t 10 | tee -a $Target-05-Directories.txt  | tee -a Scanner.log
gobuster -k -u https://$Target/ -w /root/BugBounty/Tools/Payloads/DirectoryList-Small.lst -q -e -t 10 | tee -a $Target-05-Directories.txt  | tee -a Scanner.log
#Medium Wordlist
#gobuster -u http://$Target/ -w /root/BugBounty/Tools/Payloads/DirectoryList-Medium.lst -q -e -t 10 | tee -a $Target-05-Directories.txt  | tee -a Scanner.log
#gobuster -k -u https://$Target/ -w /root/BugBounty/Tools/Payloads/DirectoryList-Medium.lst -q -e -t 10 | tee -a $Target-05-Directories.txt  | tee -a Scanner.log
#Large Wordlist
#gobuster -u http://$Target/ -w /root/BugBounty/Tools/Payloads/DirectoryList-Large.lst -q -e -t 10 | tee -a $Target-05-Directories.txt  | tee -a Scanner.log
#gobuster -k -u https://$Target/ -w /root/BugBounty/Tools/Payloads/DirectoryList-Large.lst -q -e -t 10 | tee -a $Target-05-Directories.txt  | tee -a Scanner.log
done
for Target in $(cat Targets.txt)
do
cat $Target-01-NmapTCP.txt | grep /tcp | grep open >> "$Target"_Ports.txt 2> /dev/null
cat $Target-02-NmapUDP.txt | grep /udp | grep open | grep -v filtered >> "$Target"_Ports.txt 2> /dev/null
(
input="$Target"_Ports.txt
while IFS= read -r port
do
echo "$Target":"$port" >> ServicesList.txt
done <         "$Target"_Ports.txt
)
rm *_Ports.txt
done
echo
echo "---------------------------------------------------------------"  | tee -a Scanner.log
echo "[+] The following services were found:" | tee -a Scanner.log
echo "---------------------------------------------------------------"  | tee -a Scanner.log
cat ServicesList.txt | tee -a Scanner.log
echo "[+] Generating post scan script"
cat ServicesList.txt | grep open | grep http | grep -v ssl | cut -d "/" -f 1 >> HTTPServices.txt
cat ServicesList.txt | grep open | grep https | grep -v ":80/" | cut -d "/" -f 1 >> HTTPSServices.txt
touch PostScan.sh
echo "#!/bin/bash" >> PostScan.sh
echo "read -p 'Open burpsuite & firefox and turn off intercept'" >> PostScan.sh
chmod +x PostScan.sh
for i in $(cat HTTPServices.txt)
do 
echo "firefox http://$i >> PostScan.sh
echo "sleep 2" >> PostScan.sh
done
for i in $(cat HTTPSServices.txt)
do 
echo "firefox https://$i >> PostScan.sh
echo "sleep 2" >> PostScan.sh
done
cd ../
zip -r Completed/$file.zip $file
